### ISSUE TITLE
NPM distribution is unusual

### ISSUE THREAD

**Issue by JKillian** [stipsan/scroll-into-view-if-needed#105]
Just tried out this package for this first time, and I'm a big fan! The native browser `scrollIntoView` was causing issues for me and this package is working perfectly.

However, I did notice the NPM distribution for this package is somewhat strange. The distributed files, specifically `dist/bundle.js` seem to contain all the dependent packages bundled together. This isn't the NPM way - ideally your distributed module should just `require` the other modules it wants to use. My friendly suggestion here is to use babel to compile your `src/index.js` file and distribute that in your final package as either `index.js` or `dist/index.js` and appropriately link to it in your `package.json`. You can still distribute the full rolled-up `dist/bundle.js` if you want, but it shouldn't be the main file.

Also, I noticed that the export in the distributed version is not a default export. So you have to do `import * as scrollIntoView from "scroll-into-view-if-needed"` instead of the examples given in the README.

Finally, I'd recommend adding the MIT license or another similar license to this package! Don't want to scare people away from using it 😄

**Comment by stipsan** [comment]
Hey, thanks a lot for your detailed report!

I wasn't aware that all the dependencies was included on NPM, that is indeed not ideal and will increase the build size of projects depending on this package!

I'll go over your related PRs right away, thanks again! 👍

**Comment by stipsan** [comment]
I just pushed out 1.0.7, is everything looking ok now?

**Comment by JKillian** [comment]
Yep, just upgraded and it's working great! Able to import your package now as your readme shows and the TypeScript typings work correctly for me out of the box as well. Thanks for releasing!

**Comment by stipsan** [comment]
Awesome! 👍
