### ISSUE TITLE
Uncaught TypeError: scrollIntoView is not a function

### ISSUE THREAD

**Issue by gdibble** [stipsan/scroll-into-view-if-needed#116]
Use: `var scrollIntoView = require('scroll-into-view-if-needed');`
And: `scrollIntoView(elm, true, app.scrollIntoViewOptions);`
Result:
![image](https://cloud.githubusercontent.com/assets/906846/24722356/557d2c56-19f8-11e7-8ed9-eb2eb643e5be.png)

**Comment by gdibble** [comment]
Seems crazy that I should have to update all my code to use `scrollIntoView.default()`

**Comment by jwuliger** [comment]
Working on a client's site and they use this plugin, and I am getting the same issue. I cannot seem to get around it. I am going to try your code @gdibble . Thanks and I agree with you.

**Comment by stipsan** [comment]
That is indeed crazy, probably a result of how the build step transforms es6 syntax to es5. I'll look into it.

**Comment by khell** [comment]
I have created pull request #121 which will revert to pre-1.0.7 behaviour.

**Comment by stipsan** [comment]
Fixed and released https://github.com/stipsan/scroll-into-view-if-needed/pull/121
