### ISSUE TITLE
Can i set a offset?

### ISSUE THREAD

**Issue by HaolinWang8** [stipsan/scroll-into-view-if-needed#126]
I have some thing floating on the screen like header. I want to set a offset to scroll more and show the content behind the floating header out.

**Comment by iwangulenko** [comment]
Maybe someone can implement this and take some code from here: https://github.com/yiminghe/dom-scroll-into-view/blob/master/src/dom-scroll-into-view.js

**Comment by bessfernandez** [comment]
Also wondering this same thing!

**Comment by iwangulenko** [comment]
Maybe implement similar to:
https://github.com/yiminghe/dom-scroll-into-view/blob/master/src/dom-scroll-into-view.js#L46

**Comment by stipsan** [comment]
Thanks to @iwangulenko and #127 this is now possible 😄

**Comment by catamphetamine** [comment]
Hi all.
I've read the readme and it says:

> offset
This was always a buggy feature and warned against using in v1 as it might get dropped. It's much safer to use CSS wrapper elements for this kind of thing.

https://github.com/stipsan/scroll-into-view-if-needed#offset

Seems that this feature has been removed in v2.
Shouldn't this issue be reopened then?
There seems to be no way to use this library on websites with `position: fixed` "floating" headers.

**Comment by catamphetamine** [comment]
Actually, seems this like not an issue: `center` should be used (not `top`) and then it doesn't matter whether there's a floating header or not.
There're issues when the input field itself is higher than the screen height (for example, a big JSON editor) but that can be worked around by setting the input max height less than screen height.
So ignore the above comment.

**Comment by stipsan** [comment]
It's also possible to solve this by applying the offsets you need and doing the scrolling yourself with a custom behavior: https://github.com/stipsan/scroll-into-view-if-needed#function
