### ISSUE TITLE
typescript typings are wrong

### ISSUE THREAD

**Issue by xaviergonz** [stipsan/scroll-into-view-if-needed#131]
Typescript, unlike babel, differentiates between default and "whole" exports, this is.
import * as X from 'X'; = require('X')
import X from 'X'; = require('X').default;

whereas in babel
import X from 'X'; = require('X').default || require('X');

the thing is that the TS typings say that the function is actually on require('X').default, but it is actually in require('X') due to this last line in the generated index.js:

module.exports = exports['default'];

something to do most probably with how rollup does it.
could the typings be fixed? or if not at least then make it actually export the function on default :)

**Comment by stipsan** [comment]
Hey thanks for reporting!

This behavior changed in #121 but the TS typings didn't get updated.
I will update the typings right away to reflect what is actually being exported by the generated build.

I've become quite a fan of TS (and have started using it on all my new projects) so later when I have a little more time on my hands I plan on refactoring the codebase here to TS.
No more outdated typings 😄
