### ISSUE TITLE
[1.2.5] Error installing (due to postinstall script)

### ISSUE THREAD

**Issue by giannisp** [stipsan/scroll-into-view-if-needed#142]
Hope this was committed by accident, latest npm published version (1.2.5) is trying to execute `yarn build` on npm/yarn install.

https://github.com/stipsan/scroll-into-view-if-needed/blob/1bb68395e691bf32907e79e8498b1899286ae09f/package.json#L25

**Comment by stipsan** [comment]
Yes that was by accident! Fixing right away!

**Comment by stipsan** [comment]
Just published 1.2.6 which uses `prepublish` instead as this was only meant to be used in the CI pipeline for testing, publishing to npm and building the docs site 😅
