### ISSUE TITLE
What happened to duration?

### ISSUE THREAD

**Issue by pelotom** [stipsan/scroll-into-view-if-needed#266]
Hi, I just upgraded to v2, which looks great, except the `duration` option seems to have gone away... is it no longer possible to specify a duration for the smooth scroll animation?

**Comment by stipsan** [comment]
Hey Tom!

The duration option is moved to smooth-scroll-into-view-if-needed to keep bundle sizes low for those who don’t need this feature. There’s more info on it in the readme: https://github.com/stipsan/scroll-into-view-if-needed/blob/master/README.md#ponyfill-smooth-scrolling

**Comment by pelotom** [comment]
Thanks for the info!
