### ISSUE TITLE
Scrolling up doesn't work with scrollMode: if-needed

### ISSUE THREAD

**Issue by icd2k3** [stipsan/scroll-into-view-if-needed#274]
👋 hey there,

After some investigation of an issue posted in `react-scroll-into-view-if-needed` [here](https://github.com/icd2k3/react-scroll-into-view-if-needed/issues/9). It looks as though there is a bug with the following behavior:

- scrolling _up_ to a target block _with_ scrollMode: 'if-needed'.

I setup this codesandbox to demonstrate: https://codesandbox.io/s/l4w26w2jz7
(note: it is in React, but I'd be happy to setup an html/css only one soon if it helps)

In this example, with scrollMode set to 'always', scroll to the bottom of the page and click this button at the bottom:
![button](https://www.dropbox.com/s/6pq9flok8kzkshc/Screenshot%202018-06-07%2014.18.12.png?raw=1)

Notice that it scrolls up to the target as expected

Now, switch to 'if-needed' and notice the button does _not_ scroll up to the target.

I'm happy to dig deeper in the near future and submit a PR if I can find the problem, but in the meantime just wanted to document it here for visibility.

Thanks for your work on this package!

**Comment by stipsan** [comment]
Hey thanks for the detailed report! I am on the go today but I will circle back in around 10 hours and have a go at it 😄 

The flaw is probably too simplistic logic here: https://github.com/stipsan/scroll-into-view-if-needed/blob/73e7d76ab7a1e678a47f3c63a0452a3e1b96f6a5/src/compute.ts#L256-L273

**Comment by stipsan** [comment]
@icd2k3 #276 should fix it. I have tested it locally as well as on the codesandbox you shared. 😄

**Comment by icd2k3** [comment]
Sweet! Thanks for the timely fix @stipsan

**Comment by stipsan** [comment]
No problem! 😄
