### ISSUE TITLE
`scrollIntoView` Promise doesn't resolve on some elements

### ISSUE THREAD

**Issue by matthew-dean** [stipsan/scroll-into-view-if-needed#344]
I discovered an apparent bug, where I have something like this:
```js
scrollIntoView([HTMLElement], {
  scrollMode: 'if-needed',
  block: 'nearest',
  boundary: document
}).then(() => { console.log('done') })
```
It appears that if the element doesn't need to be scrolled into view (or some other reason?), then the Promise will never resolve. Even if I change `.then()` to `.finally()`, nothing happens. No console.log is output. Meaning I can't chain `scrollIntoView`s.

I didn't have this problem until the element I needed to check if it needed to be scrolled into view was sometimes the same height as the document.

**Comment by stipsan** [comment]
Hey there!

Are you talking about `smooth-scroll-into-view-if-needed`?

**Comment by matthew-dean** [comment]
@stipsan Yes, that's what I'm using.

**Comment by stipsan** [comment]
Alright. Then it's for sure a bug. It's always returning a Promise.all:
https://github.com/stipsan/smooth-scroll-into-view-if-needed/blob/c8aa5a2d23541c8f24921f0196ece43843c58f0d/src/index.ts#L111-L125

If `scrollMode: 'if-needed'` is breaking the behavior it sounds like it's returning something other than an empty array. Gonna check it out, thanks for the report! 😄

**Comment by stipsan** [comment]
I just released [v1.1.13](https://github.com/stipsan/smooth-scroll-into-view-if-needed/releases/tag/v1.1.13) with a fix, let me know if it works 😄

**Comment by stipsan** [comment]
I'm open for feedback on what is returned when the promise resolved. It might make sense to include the same array of actions that it's mapping through?

**Comment by matthew-dean** [comment]
Thanks for the fast turnaround! It works! ^_^

**Comment by matthew-dean** [comment]
What it passes to the `then()` function is irrelevant for me. I just need to know when the Promise resolved.

**Comment by stipsan** [comment]
Alright, good news! 😄👍

**Comment by matthew-dean** [comment]
One thing that I'm seeing now. Although now an element that doesn't need scrolling returns a promise, it only _resolves_ after the timeout, even though no scrolling happened. I would expect that if no scrolling needs to happen, then it resolves immediately.

**Comment by stipsan** [comment]
Good catch! I'll take care of it right after https://github.com/stipsan/compute-scroll-into-view/issues/17 😄
