### ISSUE TITLE
Animated scroll (with duration) in IE is jerky

### ISSUE THREAD

**Issue by gdibble** [stipsan/scroll-into-view-if-needed#39]
I noticed that with IE10 and adding a duration option, the scroll effect is really jerky. Of course this doesn't seem to happen with any other browser. :smirk:

**Comment by stipsan** [comment]
Hi @gdibble,

Thanks for reporting!
The animation is not done by this module though, it's done by this package: https://github.com/anvaka/amator
If you report it there, I'll get notified by greenkeeper when `amator` publishes a new version and I'll publish a new version of `scroll-into-view-if-needed` for you with the fix 😄
