### ISSUE TITLE
Angular production support

### ISSUE THREAD

**Issue by floAtEbcont** [stipsan/scroll-into-view-if-needed#463]
When importing your lib to an angular project (I tried it with 6.1.9 with a simple empty project created with `ng new`) and running `ng serve` it works fine.

When I run `ng serve --prod` though, calling `scrollIntoView` just does nothing. There are no errors on compilation or at runtime, but apparently minification/uglification destroys something essential.

**Comment by stipsan** [comment]
Could you make a reproduction repo of it? Or a codesandbox?

ons. 3. okt. 2018 kl. 15:37 skrev floAtEbcont <notifications@github.com>:

**Comment by floAtEbcont** [comment]
@stipsan Sure. :-)

```bash
git clone https://github.com/floAtEbcont/scroll-into-view-if-needed-angular-test.git
cd scroll-into-view-if-needed-angular-test
npm install
npm run start
```

-> This will give you a working version at http://localhost:4200/ (If you click the button, it will scroll down to the div)

However, if you run `npm run start -- --prod` instead, the button will just do nothing (No errors on compilation or at runtime).
I'm using the latest npm (6.4.1) on Linux.

**Comment by stipsan** [comment]
Thanks! 😄 Checking it now!

**Comment by stipsan** [comment]
It appears to be the code is actually not missing. But it's failing to calculate the scrolling correctly.

If you use `behavior: actions => console.log(actions)` you can see that it returns an empty `[]`. I haven't verified manually wether uglify is eliminating anything it shouldn't, but so far it doesn't appear to be.

I will continue looking into it tomorrow. I suspect it's somehow CSS related, but unsure how that's possible as it looks like there's no difference on the dom or css depending on the env? I'll also go through the code manually to verify wether the minifier is deleting something it shouldn't.

**Comment by floAtEbcont** [comment]
@stipsan Yeah - thank you so much for you swift fix! :smiley: npm v2.2.19 of scroll-into-view-if-needed works perfectly for me!

**Comment by stipsan** [comment]
Awesome 👍 😄

**Comment by RichieRock** [comment]
Thank you for fixing this! I had the exact same issue and was wondering quite a long time why it's not working in production until I decided to come to this github issues page and found this :)

Thanks a lot!

**Comment by Ludevik** [comment]
Thank you. I am now able to set "buildOptimizer": true for my prod builds ;)
