### ISSUE TITLE
Scroll element inside a iframe stop working when update to version 2.2.19

### ISSUE THREAD

**Issue by minhtranite** [stipsan/scroll-into-view-if-needed#480]
I have a React component render list chidrent inside a iframe (fixed height and scrollable). When i click on a child element i want to scroll it to center viewport. I use scroll-into-view-if-needed and it worked. but after update to version 2.2.19 it stop work without any error message. It work again when downgrade to version 2.2.15

**Comment by stipsan** [comment]
Hey and thanks for the report! I’ll give this a look as soon as I can 🙂

**Comment by stipsan** [comment]
I found an issue with this check that got added in version `2.2.17`:

https://github.com/stipsan/scroll-into-view-if-needed/blob/82929e919e874461866eaa8178f3f3c0251bd17c/src/index.ts#L67-L70

I'm changing this to https://github.com/stipsan/scroll-into-view-if-needed/blob/4e70a909aa96c9da20c356c81ce1eec84d019b24/src/index.ts#L67 in #482 

A new version with the fix will be automatically released soon 🙂

**Comment by stipsan** [comment]
It's out: https://github.com/stipsan/scroll-into-view-if-needed/releases/tag/v2.2.20

**Comment by minhtranite** [comment]
Updated to version 2.2.20 and the bug gone. Thank you!

**Comment by stipsan** [comment]
Great! 👍
