### ISSUE TITLE
Snaps instead of scrolling smoothly.

### ISSUE THREAD

**Issue by MaximilianLloyd** [stipsan/scroll-into-view-if-needed#612]
The scrolling works, but it does not happen smoothly. It just snaps.

**Comment by 0xdevalias** [comment]
Based on how you've described it, this is an explicit feature, and already documented.

See the following:
- https://github.com/stipsan/scroll-into-view-if-needed#ponyfill-smooth-scrolling
- https://github.com/stipsan/smooth-scroll-into-view-if-needed

**Comment by NeliHarbuzava** [comment]
Maybe you should enable smooth scrolling in your browser (for Chrome go to [chrome://flags/#smooth-scrolling](chrome://flags/#smooth-scrolling) )
